modLoader="javafml"
loaderVersion="[47,)"
license="BSD 3-Clause"
issueTrackerURL="https://github.com/candlestickphone/slim_pickings/issues"

[[mods]]
modId="slim_pickings"
version="1.0"
displayName="Slim Pickings"
logoFile="looker.png"
credits="shamuel"

description='''
A simple, vanilla-style item pickup mod.
'''

[[dependencies.slim_pickings]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.slim_pickings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"